on:
  push:
    branches:
    - main
    - dev

name: Build and Push to ECR
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
  IMAGE_REPOSITORY_NAME: flask_test
  CONTAINER_IMAGE: flask_test:${{ github.run_number }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - name: Install AWSCLI Dependencies
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Setup ECR
      run: |
        # Login to AWS ECR
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./app

    - name: Push
      #if: github.ref == 'refs/heads/main'
      run: |
        # Push image to AWS ECR
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE

    - name: Update Image Version in deployment.yaml
      #if: github.ref == 'refs/heads/main'
      uses: fjogeleit/yaml-update-action@main
      with:
        # valueFile: 'manifests/deployment.yaml'
        # propertyPath: 'spec.template.spec.containers.0.image'
        # repository: mainakmb/gitops-argocd
        # updateFile: 'true'
        # value: flask_test:${{ github.run_number }}
        # commitChange: 'false'
        # branch: deployment/flask_test:${{ github.run_number }}
        # targetBranch: main
        # createPR: 'false'
        # message: 'Update Image Version to flask_test:${{ github.run_number }}'
        # token: ${{ secrets.GH_TOKEN }}

        # valueFile: 'manifests/deployment.yaml'
        # propertyPath: 'spec.template.spec.containers.0.image'
        # value: 'flask_test:${{ github.run_number }}'
        # repository: mainakmb/gitops-manifests
        # branch: deployment/flask_test
        # targetBranch: deployment/flask_test
        # updateFile: true
        # createPR: false
        # commitChange: true
        # message: 'Update Image Version to flask_test:${{ github.run_number }}'
        # token: ${{ secrets.TOKEN_GITHUB }}

        valueFile: './manifests/deployment.yaml'
        propertyPath: 'spec.template.spec.containers.0.image'
        value: 'flask_test:${{ github.run_number }}'
        commitChange: false
        updateFile: true
