on:
  push:
    branches:
    - main
    - dev

name: Build and Push to ECR
env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETE_ID }}
  IMAGE_REPOSITORY_NAME: flask_test
  CONTAINER_IMAGE: flask_test:${{ github.run_number }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - name: Install AWSCLI Dependencies
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    
    - name: Setup ECR
      run: |
        # Login to AWS ECR
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME
    - name: Build and tag the image
      run: |
        # Build and tag the image
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./app

    - name: Push image in ECR
      #if: github.ref == 'refs/heads/main'
      run: |
        # Push image to AWS ECR
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE

    - name: Update Image Version in deployment manifest
      #if: github.ref == 'refs/heads/main'
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'manifests/deployment.yaml'
        propertyPath: 'spec.template.spec.containers.0.image'
        repository: mainakmb/ArgoCD_manifests
        updateFile: true
        value: '${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flask_test:${{ github.run_number }}'
        commitChange: true
        branch: main
        masterBranchName: 'dev'
        createPR: 'false'
        message: 'Update Image Version to flask_test:${{ github.run_number }}'
        token: ${{ secrets.GH_TOKEN }}

    - name: Push other yaml file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_TOKEN }}
      with:
        source_file: 'manifests/deployment.yaml'
        destination_repo: 'mainakmb/ArgoCD_manifests'
        destination_folder: 'manifests'
        user_email: 'mainakbiswasmb@gmail.com'
        user_name: 'Mainak Biswas'
        commit_message: 'svc.yaml Added'
